# Generated by Django 3.0.6 on 2020-07-06 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_prod_aluguel',
            name='dt_final',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 6, 13, 11, 52, 457384), null=True, verbose_name='Data final da apresentação'),
        ),
        migrations.AlterField(
            model_name='cad_prod_aluguel',
            name='dt_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 6, 13, 11, 52, 457384), null=True, verbose_name='Data inicio da apresentação'),
        ),
        migrations.AlterField(
            model_name='cad_prod_bebida',
            name='dt_final',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 6, 13, 11, 52, 456386), null=True, verbose_name='Data final da apresentação'),
        ),
        migrations.AlterField(
            model_name='cad_prod_bebida',
            name='dt_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 6, 13, 11, 52, 456386), null=True, verbose_name='Data inicio da apresentação'),
        ),
        migrations.AlterField(
            model_name='carrinho_bebidas',
            name='dt_inclusao',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 6, 13, 11, 52, 458388), null=True, verbose_name='Data de inclusão no carrinho'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dt_cadastro',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 6, 13, 11, 52, 454388), null=True, verbose_name='Data cadastro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dt_abertura',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 6, 13, 11, 52, 458388), null=True, verbose_name='Data de abertura do pedido'),
        ),
    ]
