# Generated by Django 3.0.6 on 2020-07-08 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepedidos', '0003_auto_20200706_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_prod_aluguel',
            name='dt_final',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 8, 12, 20, 50, 280017), null=True, verbose_name='Data final da apresentação'),
        ),
        migrations.AlterField(
            model_name='cad_prod_aluguel',
            name='dt_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 8, 12, 20, 50, 280017), null=True, verbose_name='Data inicio da apresentação'),
        ),
        migrations.AlterField(
            model_name='cad_prod_bebida',
            name='dt_final',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 8, 12, 20, 50, 280017), null=True, verbose_name='Data final da apresentação'),
        ),
        migrations.AlterField(
            model_name='cad_prod_bebida',
            name='dt_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 8, 12, 20, 50, 279018), null=True, verbose_name='Data inicio da apresentação'),
        ),
        migrations.AlterField(
            model_name='carrinho_bebidas',
            name='dt_inclusao',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 8, 12, 20, 50, 282016), null=True, verbose_name='Data de inclusão no carrinho'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dt_cadastro',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 8, 12, 20, 50, 277018), null=True, verbose_name='Data cadastro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='endereco_entrega',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='endereco_entrega',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dt_abertura',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 8, 12, 20, 50, 281017), null=True, verbose_name='Data de abertura do pedido'),
        ),
    ]
