# Generated by Django 3.0.6 on 2020-07-08 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepedidos', '0004_auto_20200708_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_prod_aluguel',
            name='dt_final',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 8, 20, 38, 37, 546218), null=True, verbose_name='Data final da apresentação'),
        ),
        migrations.AlterField(
            model_name='cad_prod_aluguel',
            name='dt_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 8, 20, 38, 37, 546218), null=True, verbose_name='Data inicio da apresentação'),
        ),
        migrations.AlterField(
            model_name='cad_prod_bebida',
            name='bebida',
            field=models.CharField(choices=[('ANTARCTICA', 'ANTARCTICA'), ('BADER', 'BADER'), ('BAVARIA', 'BAVARIA'), ('BOHEMIA', 'BOHEMIA'), ('BRAHMA', 'BRAHMA'), ('BUDWEISER', 'BUDWEISER'), ('CARACU', 'CARACU'), ('CORONA', 'CORONA'), ('CRYSTAL', 'CRYSTAL'), ('DEVASSA', 'DEVASSA'), ('EISENBAHN', 'EISENBAHN'), ('GLACIAL', 'GLACIAL'), ('HEINEKEN', 'HEINEKEN'), ('ITAIPAVA', 'ITAIPAVA'), ('KAISER', 'KAISER'), ('PETRA', 'PETRA'), ('SCHIN', 'SCHIN'), ('SKOL', 'SKOL'), ('STELLA', 'STELLA'), ('TERESOPOLIS', 'TERESOPOLIS'), ('TIJUCA', 'TIJUCA')], help_text='Selecione o produto', max_length=100, verbose_name='Bebida'),
        ),
        migrations.AlterField(
            model_name='cad_prod_bebida',
            name='dt_final',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 8, 20, 38, 37, 545218), null=True, verbose_name='Data final da apresentação'),
        ),
        migrations.AlterField(
            model_name='cad_prod_bebida',
            name='dt_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 8, 20, 38, 37, 545218), null=True, verbose_name='Data inicio da apresentação'),
        ),
        migrations.AlterField(
            model_name='cad_prod_bebida',
            name='url_imagem',
            field=models.CharField(blank=True, help_text='Digite a url de endereço da imagem', max_length=2000, null=True, verbose_name='URL da Imagem do Produto'),
        ),
        migrations.AlterField(
            model_name='carrinho_bebidas',
            name='dt_inclusao',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 8, 20, 38, 37, 547217), null=True, verbose_name='Data de inclusão no carrinho'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dt_cadastro',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 8, 20, 38, 37, 542219), null=True, verbose_name='Data cadastro'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dt_abertura',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 8, 20, 38, 37, 547217), null=True, verbose_name='Data de abertura do pedido'),
        ),
    ]
