# Generated by Django 3.0.6 on 2020-07-10 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepedidos', '0006_auto_20200708_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_prod_aluguel',
            name='dt_final',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 10, 14, 39, 46, 582650), null=True, verbose_name='Data final da apresentação'),
        ),
        migrations.AlterField(
            model_name='cad_prod_aluguel',
            name='dt_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 10, 14, 39, 46, 582650), null=True, verbose_name='Data inicio da apresentação'),
        ),
        migrations.AlterField(
            model_name='cad_prod_bebida',
            name='dt_final',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 10, 14, 39, 46, 581650), null=True, verbose_name='Data final da apresentação'),
        ),
        migrations.AlterField(
            model_name='cad_prod_bebida',
            name='dt_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 10, 14, 39, 46, 581650), null=True, verbose_name='Data inicio da apresentação'),
        ),
        migrations.AlterField(
            model_name='carrinho_bebidas',
            name='dt_inclusao',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 10, 14, 39, 46, 584649), null=True, verbose_name='Data de inclusão no carrinho'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dt_cadastro',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 10, 14, 39, 46, 579651), null=True, verbose_name='Data cadastro'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dt_abertura',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 10, 14, 39, 46, 583650), null=True, verbose_name='Data de abertura do pedido'),
        ),
    ]
